# Generated by Django 5.0.6 on 2024-07-09 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="post/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
